version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flight_booking_mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hoidanit
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3307"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 2

volumes:
  mysql_dev_data:
